### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by graygilmore** [ltk/kurtz-kloud#2]
Failing on `npm start`. Here's what my log looks like (also contains node and npm version numbers):

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@1.4.9
3 info using node@v0.10.28
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart kurtz-kloud@0.1.0
6 info start kurtz-kloud@0.1.0
7 verbose unsafe-perm in lifecycle true
8 info kurtz-kloud@0.1.0 Failed to exec start script
9 error kurtz-kloud@0.1.0 start: `node .`
9 error Exit status 8
10 error Failed at the kurtz-kloud@0.1.0 start script.
10 error This is most likely a problem with the kurtz-kloud package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node .
10 error You can get their info via:
10 error     npm owner ls kurtz-kloud
10 error There is likely additional logging output above.
11 error System Darwin 13.1.0
12 error command "node" "/usr/local/bin/npm" "start"
13 error cwd /Users/graygilmore/kurtz-kloud
14 error node -v v0.10.28
15 error npm -v 1.4.9
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]
```

And here's everything from iTerm:

```
➜  kurtz-kloud git:(master) ✗ npm start

> kurtz-kloud@0.1.0 start /Users/graygilmore/kurtz-kloud
> node .


fs.js:1051
    throw errnoException(process._errno, 'watch');
          ^
Error: watch ENOENT
    at errnoException (fs.js:1019:11)
    at FSWatcher.start (fs.js:1051:11)
    at Object.fs.watch (fs.js:1076:11)
    at EventEmitter.Directory.watch (/Users/graygilmore/kurtz-kloud/lib/directory.js:12:6)
    at App.start (/Users/graygilmore/kurtz-kloud/app.js:12:18)
    at Object.<anonymous> (/Users/graygilmore/kurtz-kloud/index.js:5:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

npm ERR! kurtz-kloud@0.1.0 start: `node .`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the kurtz-kloud@0.1.0 start script.
npm ERR! This is most likely a problem with the kurtz-kloud package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .
npm ERR! You can get their info via:
npm ERR!     npm owner ls kurtz-kloud
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/graygilmore/kurtz-kloud
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/graygilmore/kurtz-kloud/npm-debug.log
npm ERR! not ok code 0
```

**Comment by graygilmore** [comment]
Oh man, simply misspelled my own name for the watch directory.

**Comment by ltk** [comment]
Perhaps the error message for a missing watch directory should be a bit more graceful (and helpful). Thanks for pointing this out!

**Comment by graygilmore** [comment]
That might be good! It'll help those of us that can't remember how to spell our own name ;)

I've run into some authentication issues as well, haven't been able to fully get it up and running yet, but at least the app is working!
